export const en = {
    translation: {
        app: {
            title: "GitDigest",
            subtitle: "AI-Powered Development Reports",
            settings: "Settings"
        },
        repo: {
            label: "Repository",
            select: "Click to Select Git Project",
            analyzing: "Analyzing...",
            valid: "Valid Git Repo",
            change: "Change"
        },
        filter: {
            title: "Filters",
            author: "Author",
            allAuthors: "All Authors",
            startDate: "Start Date",
            endDate: "End Date",
            generate: "Generate Report",
            generating: "Generating...",
            configureFirst: "Configure LLM First",
            config: "Config",
            llmReady: "LLM Ready",
            noKey: "No Key"
        },
        report: {
            tabReport: "Report",
            tabCommits: "Source Commits",
            copy: "Copy Markdown",
            copied: "Report copied to clipboard!",
            generatedBy: "Generated by",
            chars: "chars",
            placeholder: {
                title: "Ready to generate",
                subtitle: "Select a repo and filters to begin"
            }
        },
        settings: {
            title: "LLM Configuration",
            provider: "Provider",
            baseUrl: "Base URL",
            apiKey: "API Key",
            model: "Model Name",
            language: "Language",
            cancel: "Cancel",
            save: "Save Configuration",
            saving: "Saving...",
            saved: "Settings saved!",
            required: "API Key is required"
        },
        toast: {
            foundCommits: "Found {{count}} commits. Generating report...",
            noCommits: "No commits found in range",
            generated: "Report Generated!",
            error: "Error: {{message}}",
            repoLoaded: "Loaded repo on branch: {{branch}}",
            notGit: "Not a valid git repository (no .git folder found)"
        }
    }
};
